name: Mirror modification/removal request / 镜像修改/删除请求
description: Request a change to existing mirror repository / 请求对已有的镜像仓库做修改
labels:
  - modify
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        欢迎向 USTC Mirror 提交对已有的镜像仓库的修改请求。如果你希望 USTC 修改已有的镜像同步配置，或移除某个镜像，请按以下模板填写。
        If you want to request USTC to modify or remove an existing mirror repository, please submit your issue using the following template.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: 先决条件 (Prerequisites)
      options:
        - label: |
            我已确认该事宜从未在 [其他 issues](https://github.com/ustclug/mirrorrequest/issues) 中讨论过。  
            I have checked that my proposal has not been discussed in [other issues](https://github.com/ustclug/mirrorrequest/issues).
          required: true
        - label: | 
            我已仔细阅读 [请求新镜像前必读](https://github.com/ustclug/mirrorrequest/issues/350)。  
            I have CAREFULLY read the [mirroring rules](https://github.com/ustclug/mirrorrequest/issues/350).
          required: true
  - type: textarea
    id: description
    attributes:
      label: 修改或删除的原因 (Reasons of the modification or removal)
    validations:
      required: true
  - type: textarea
    id: upstream
    attributes:
      label: 配置方法 (Configuration method)
    validations:
      required: true
  - type: input
    id: mirror_size
    attributes:
      label: 修改后的镜像大小 (Mirror size after modification)
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: 备注 (Note)
    validations:
      required: false
